GET http://localhost:3333/courses

###

POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curos FullStack2"
}

### 
GET http://localhost:3333/courses/01d2605c-53f4-4c93-92cb-29d9942645cc