# fly.toml app configuration file generated for desafio-node on 2025-08-25T12:23:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'desafio-node'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
